artifact_location: file:///c:/Users/Emmanuel/Documents/openclassroom/projet7/Projet_7_EJ/notebooks/your_tracking_uri/0
creation_time: 1746464955964
experiment_id: '0'
last_update_time: 1746464955964
lifecycle_stage: active
name: Default
